server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.*"
  mail:
    host: ${SMTP_HOST:sandbox.smtp.mailtrap.io}
    port: ${SMTP_PORT:2525}
    username: ${SMTP_USERNAME:user}
    password: ${SMTP_PASSWORD:pass}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
