server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:bookingdb}
    username: ${DB_USER:booking}
    password: ${DB_PASS:booking}
    jpa:
      hibernate:
        ddl-auto: validate
    flyway:
      enabled: true
    kafka:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        group-id: booking-service
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "com.example.*"
